### ISSUE TITLE
Add YAML examples for all resources required

### ISSUE THREAD

**Issue by mauriciocirelli** [rdvansloten/cert-manager-key-vault-sync#3]
Hi!

It is lovely that you have developed this very important feature that was missing from cert-manager. Thank you for that!

I would like to try, but I think it is harder to understand what is happening when we use helm charts..
Since this requires just a few resources, I would like to suggest to add YAML examples in the README.md file for the minimum needed, like ServiceAccount and Deployment.

Ingress, ClusterRole and other stuff is already well documented in the cert-manager and Azure repositories, so I would just point the links to them.

Again, thank you!

**Comment by rdvansloten** [comment]
Yeah I can do that! In the meantime you could render the output of the Helm chart using `helm template cert-manager-key-vault-sync
    oci://docker.io/rdvansloten/cert-manager-key-vault-sync --values ./charts/cert-manager-key-vault-sync/values.yaml \
    --namespace cert-manager-key-vault-sync > output.yaml` 

And just snag the ServiceAccount and the Deployment from the output.yaml. Be mindful that you then need to configure your own Role Bindings that match the permissions rendered by the Helm template, or the SA can't access the Secrets. The Helm chart currently installs/renders the absolute bare minimum it needs to run the app.

**Comment by mauriciocirelli** [comment]
That's true, we need the ClusterRole and ClusterRoleBinding so the SA can access the secrets within the cluster.

I did the command you suggested and got the template files. I can work from there.

Thanks!

**Comment by rdvansloten** [comment]
@mauriciocirelli This was added to README.md 🙂 closing this issue!
